# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(help_text='Unique part number for reordering.', max_length=6)),
                ('address', models.CharField(help_text='Postal address of customer.', max_length=200)),
                ('phone', models.CharField(help_text='Daytime contact details of customer.', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
